platform :ios, '8.0'
use_frameworks!

target 'CDMSegmentedControl_Example' do
  pod 'CDMSegmentedControl', :path => '~/Documents/MyFirstCocoaPod/CDMSegmentedControl'

  target 'CDMSegmentedControl_Tests' do
    inherit! :search_paths

    
  end
end
