# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example

branches:
  only:
    - master
git:
  submodules: false

matrix:
  include:
    - osx_image: xcode7.3
      env: TRAVIS_SWIFT_VERSION=2.2

script:
#- set -o pipefail && xcodebuild test -workspace Example/CDMSegmentedControl.xcworkspace -scheme CDMSegmentedControl-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint

script: xcodebuild -workspace "Example/CDMSegmentedControl.xcworkspace" -scheme "CDMSegmentedControl-Example" -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
